version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db # Mount data volume named 'mongodb-data' to store the MongoDB data
    ports:
      - "27017:27017"
volumes:
  mongodb-data: # Define the 'mongodb-data' volume